services:

  feature-flags-prod:
    image: ducnta99/go-feature-flags:0.2.0
    container_name: todos-app-prod
    volumes:
      - ./configs/prod/config.yml:/app/configs/config.yml:ro
    environment:
      CONFIG_PATH: /app/configs/config.yml
    ports:
      - "8080:9420" 
    depends_on:
      db_prod:
        condition: service_healthy
      unleash:
        condition: service_healthy
    networks:
      - localnet

  migrate_prod:
    image: migrate/migrate
    container_name: migrate-prod
    depends_on:
      db_prod:
        condition: service_healthy
    entrypoint:
      [
        "sh",
        "-c",
        "migrate -path=/migrations -database=postgres://${DB_USERNAME}:${DB_PASSWORD}@db_prod:5432/${DB_DATABASE}?sslmode=disable up",
      ]
    volumes:
      - ./migrations/prod:/migrations
    networks:
      - localnet

  db_prod:
    image: postgres:16.4-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /data/postgres
    env_file:
      - .env
    volumes:
      - .docker/prod/pg-data:/data/postgres
    networks:
      - localnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 15s
      timeout: 15s
      retries: 10
      start_period: 10s

  # setup development environment
  feature-flags-dev:
    image: ducnta99/go-feature-flags:0.2.0
    container_name: todos-app-dev
    volumes:
      - ./configs/dev/config.yml:/app/configs/config.yml:ro
    environment:
      CONFIG_PATH: /app/configs/config.yml
    ports:
      - "8081:9420" 
    depends_on:
      db_dev:
        condition: service_healthy
      unleash:
        condition: service_healthy
    networks:
      - localnet

  db_dev:
    image: postgres:16.4-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /data/postgres
    env_file:
      - .env
    volumes:
      - .docker/dev/pg-data:/data/postgres
    networks:
      - localnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 15s
      timeout: 15s
      retries: 10
      start_period: 10s

  migrate_dev:
    image: migrate/migrate
    container_name: migrate-dev
    depends_on:
      db_dev:
        condition: service_healthy
    entrypoint:
      [
        "sh",
        "-c",
        "migrate -path=/migrations -database=postgres://${DB_USERNAME}:${DB_PASSWORD}@db_dev:5432/${DB_DATABASE}?sslmode=disable up",
      ]
    volumes:
      - ./migrations/dev:/migrations
    networks:
      - localnet

  # Setup unleash
  unleash:
    container_name: unleash
    image: unleashorg/unleash-server:7.4.0
    ports:
      - "4242:4242"
    environment:
      DATABASE_URL: postgres://unleash:unleash@unleash_db:5432/unleash
      DATABASE_SSL: "false"
      LOG_LEVEL: "warn"
      INIT_FRONTEND_API_TOKENS: default:development.unleash-insecure-frontend-api-token,default:production.unleash-insecure-frontend-api-token
      INIT_BACKEND_API_TOKENS: default:development.unleash-insecure-api-token,default:production.unleash-insecure-api-token
    depends_on:
      unleash_db:
        condition: service_healthy
    networks:
      - localnet
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4242/health || exit 1
      interval: 20s
      timeout: 1m
      retries: 10
      start_period: 1m

  unleash_db:
    container_name: unleash-postgres
    image: postgres:16.4-alpine
    environment:
      POSTGRES_DB: unleash
      POSTGRES_USER: unleash
      POSTGRES_PASSWORD: unleash
    volumes:
      - ./.docker/unleash_pgdata:/var/lib/postgresql/data
    networks:
      - localnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U unleash -d unleash"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s

networks:
  localnet:
    driver: bridge
