app:
  environment: production
  name: todo-app
  version: v0.2.0

db:
  host: db_prod
  port: 5432
  user: test
  pass: test
  dat_name: example

# config unleash follow the official document: 
# https://docs.getunleash.io/sdks/go
unleash:
  backend_url: http://unleash:4242/api
  token: default:production.unleash-insecure-api-token
